### ISSUE TITLE
A connection attempt failed

### ISSUE THREAD

**Issue by rkaderli** [timdorr/tesla-api#220]
I'm using a service on Azure to gather Tesla data for almost a year successfully now. client_id and client_secret as available on https://tesla-api.timdorr.com/api-basics/authentication

Recently Post for "/oaouth/token?grant_type=password" fails from the Azure server with the exception: “**A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond**”

Strange, that from development environment the same code still works and gets valid token successfully with exactly the same credentials.

Could it be that Tesla firewalls certain IP? 
Are you aware of any limitation regarding amount of queries? Could a query every 15s get us blacklisted?

I'm grateful for any hint or possibly a contact that could help!

**Comment by timdorr** [comment]
You shouldn't be authenticating too often. There is rate limiting on the API, but it's on a per-authentication basis, as far as I can tell. Therefore, there is likely a separate rate limit for the unauthenticated endpoints, which is mostly the /oauth ones. I would make sure you're hanging on to the refresh token and refreshing your access token when it expires (vs. doing a password grant).

**Comment by tekgiant** [comment]
@timdorr @rkaderli This isn't a rate limiting issue. I'm fairly certain this is either an Azure issue, or Tesla is blocking Azure IPs for some reason... I've been working on an app that has some APIs hosted in Azure to talk to Tesla because of CORS issues when trying to do client requests. I can hit every endpoint without fail on my locally running Function App; but, once deployed to Azure, every request to Tesla gets this response: 
_A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond._

I'm pretty certain it's not a code issue either. I've written multiple server applications, both nodejs and .net core. Both work fine locally, but not when deployed.

If either of you have managed to get client-side requests to work (I'm assuming with some sort of configuration to avoid CORS problems), please let me know.

Also, small FYI @timdorr . I thought this might have been because my server isn't sending a User-Agent header, but my locally running server has never needed a User-Agent header for requests to work, and I still receive these connections errors regardless of including the User-Agent header or not; so you may want to update the documentation, because it would seem this header is not actually required.

**Comment by tekgiant** [comment]
Update to my previous post.... I created an AWS Lambda function to attempt the same thing and it also doesn't work there either.

**Comment by timdorr** [comment]
That sounds like something is wrong with your code. I regularly communicate with Tesla's API from AWS datacenters.

**Comment by tekgiant** [comment]
@timdorr Mind sharing what AWS Service you're using?

**Comment by timdorr** [comment]
Heroku, but they use AWS as their underlying service provider.

**Comment by tekgiant** [comment]
I meant which **AWS** service? I.e. Lambda, S3, Lightsail, EC2, etc?

**Comment by timdorr** [comment]
Heroku uses EC2 instances for the most part. They all run in the same IP space.

**Comment by tekgiant** [comment]
I have a feeling there is something else going on here. It's obviously possible I'm doing something wrong in code, but I have now 2 different applications that both work fine locally, but when deployed to AWS and Azure respectively, do not work - and considering someone else is having a similar, "works locally but not deployed" situation, I highly doubt it's not something wrong in my code.

**Comment by rkaderli** [comment]
As mentioned initially  the code was working for a Year at Azure. Then stopped working with the error pointing to network/firewall level issue: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond".
It even came back working for about 2 days. Afterwards I could not connect from Azure also when setting up a from different App. Never have any problem connecting from my dev machine.

**Comment by ltfiend** [comment]
Just did a test with some code I've been running for a long time at home.  Deployed it to an EC2 and it didn't work.   Traffic shows no responses coming back from the Tesla servers.   I would concur that they are blocking AWS.

**Comment by timdorr** [comment]
Ah, they are blocking as of a month ago. My bad. If you go through a proxy, you shouldn't have an issue.

**Comment by tekgiant** [comment]
Hmm, that's concerning. Makes me wonder if they're going to start blocking other IPs as well. We could use a proxy, but I wonder how long it would be before that gets blocked.

@timdorr Are you currently using a proxy? If so, which one?

**Comment by timdorr** [comment]
You can set something up in Digital Ocean or OVH for cheap.
