### ISSUE TITLE
Support for option codes

### ISSUE THREAD

**Issue by fyllepo** [timdorr/tesla-api#225]
Hi guys,

Uhm, sorry for raising an issue -- I'm more or less seeking information on what the deal is with OptionCodes, been doing lots of testing and our Tesla X test account returns lots of wrong features, I then realised that these are all based off of the Model 3, and saw you had mentioned this on your options code page!

Couple of queries on this, if I may please:

1. The mobile apps can't be displaying vehicle features based on the returned codes right? or else the apps would be wrong!
2. Could they be making further requests to a dedicated option code translation endpoint? seems plausible for this to exist.
3. What processes were taken to determine the endpoint calls that are currently documented -- were app requests been traced/logged in some way, like wireshark or something? presumably the endpoints we have documented aren't the full picture here?

Thanks a lot!

Phil

**Comment by timdorr** [comment]
The app uses other endpoints, notably vehicle_data, which has all of the information they need. This is easier because they are simple fields, rather than an opaque set of codes. From what I understand, they used to come from Salesforce data, which was keyed in manually by sales staff and was prone to errors. They've since moved on from this, hence all vehicles having the same ones now. I wouldn't rely on them, as the data endpoint is generally more up to date.
