### ISSUE TITLE
Swagger / OpenAPI

### ISSUE THREAD

**Issue by davidglassborow** [timdorr/tesla-api#312]
Just a though really, would it be straight forward to generate an OpenAPI description of the API from your Ruby implementation/docs ?  I was thinking that would help all other language developers, they could auto-generate their API implementations using OpenAPI / Swagger tools.

**Comment by timdorr** [comment]
It doesn't exactly follow REST semantics, so you'd probably run up against some edge cases that OpenAPI isn't going to handle well. That's why I renamed it from the REST API to the JSON API. 

If you want to give it a try and submit a PR, I can see about merging that in here. It's not something I'm planning on doing myself, so I'm going to close this out for now.
