### ISSUE TITLE
vehicle_id versus id

### ISSUE THREAD

**Issue by benhannel** [timdorr/tesla-api#32]
In the apiary documentation, almost all the methods require a "vehicle_id" parameter, however it actually seems this must be the value labeled "id" in the list of all vehicles.

**Comment by timdorr** [comment]
Could you submit a PR with changes?

**Comment by Vortec4800** [comment]
In the vehicles list API there is a `vehicle_id` param and an `id`/`id_s` param and they are different values. Does anyone know what the difference is?

**Comment by timdorr** [comment]
The `vehicle_id` is a GUID of some sort for the vehicle. There are a few different APIs (info/command JSON API, the streaming telematics, the autopark system), so it's used as a unique identifier for the vehicle everywhere. It may come from some internal ERP system.

The `id` is because the JSON API runs on a Rails application. Rails' ORM (ActiveRecord) always adds an auto-incrementing `id` field to every model. It also makes it easy to look up a model by this id (`Vehicle.find(params[:id])`), so it's passed around as a convenience. 

When you need to hop systems, the `vehicle_id` is used. When you are sticking to just the JSON API, then you can use `id`.

**Comment by Vortec4800** [comment]
Great info. Thanks!

**Comment by artiestie** [comment]
I agree there are a few starved areas that could be improved in the api.  I have not written any down yet, but from what I remember:

- vehicle_id vs vehicles' id (this issue)

- request timeout time

- some responses are not full / up to date? (climate state the one that I noticed)

- wake up car lacks detail of what it does / who needs it

Love the progress so far, I'll PR when I get the time

**Comment by timdorr** [comment]
Finally added a blurb on this! https://tesla-api.timdorr.com/api-basics/vehicles

I'm cleaning up the other usages as I go too.
