### ISSUE TITLE
Document new 4.x app endpoints

### ISSUE THREAD

**Issue by timdorr** [timdorr/tesla-api#445]
7aa99c1567237b5219a34804d3636a95f5cfa101 and 17500b0d64dcbbe34949dddc007e4399df531a3d added a bunch of new endpoints from the latest app releases. We should get those documented.

I'm held back from testing some of the ones requiring 2021.36, as I don't have that on my car currently. I'm expecting a new Model S in the coming weeks, so hopefully either that gets it or they roll it out to my current car by then.

**Comment by corsair** [comment]
With the release of the 4.1.0 update, there's two new domain endpoints that provide a trove of new data:

ownership.tesla.com (for account, payments, charging)
and
akamai-apigateway-vfx.tesla.com (for Safety Score and other not yet discovered endpoints)

Here's a complete walkthrough on how to access the Safety Score, but also applies to every new endpoint that isn't on the owner-api.teslamotors.com domain.

This comes with a new caveat that these new endpoints and API calls require the SSO Access Token and no longer utilizes the Owner's API Token (OAT). The downside to this is that this access token must be updated every eight hours, for the request to not send a 401 Unauthorized error. If the token has expired, worry not, you simply will need to regenerate a new access token using the non-expiring SSO refresh token and you're all good to go again.

Another benefit to this is that you no longer need to generate OATs, since all of the owner API calls can also utilize this SSO access token.

Note: It appears that for some Tesla Accounts, Tesla changed the guid of the JWT so if you experience 403 errors (with a bunch of garbled non-UTF letters), you'll need to regenerate your refresh SSO token again. This is expected to impact a significant number of accounts, as in practice, it's occurred for 3/7 Tesla Accounts so far.

---
### Safety Score

To access the Safety Score metrics, you will be using the following base:
``https://akamai-apigateway-vfx.tesla.com``

To access the daily metrics and overall score/metrics, you'll use the following endpoint:
``/safety-rating/daily-metrics``

This URL also requires a handful of mandatory URL parameters which will result in an error if excluded.
vin=<vin>
timezone=<timezone> in America/Chicago format.
deviceLanguage=en
deviceCountry=US
appVersion=4.1.0-663
hasInsurance=false

---
### Other Endpoints
All of the new endpoints on the ``ownership.tesla.com`` require the following URL parameters:
vin=<vin>
deviceCountry=<uppercase two letter country code, ie: US>
devideLanguage=<supported two letter language code, ie: en>

**Comment by ramonsmits** [comment]
How does `set_charging_amps` work? I tried posting a JSON body with `charging_amps` but getting a failure.

**Comment by matfroh** [comment]
I tried to play with the new endpoint `charge_history`, but will only get an empty result.
`api/1/vehicles/{vehicle_id}/charge_history` should show the same than Charge Stats in the app.
`{
    "response": "{}\n"
}`

There must be some query parameters to add.
To what I found out, it stores the values in 31 days and that is that way it's rendered in the app.
Anyone has more luck with it?

**Comment by Panda88CO** [comment]
Is the wake_up longer working - I get a page not found when trying ?

**Comment by FashionCStar** [comment]
> 

I faced same issue with you.
Did you find the solution?

**Comment by FashionCStar** [comment]
> I tried to play with the new endpoint `charge_history`, but will only get an empty result. `api/1/vehicles/{vehicle_id}/charge_history` should show the same than Charge Stats in the app, but it only returns this:
> 
> `{ "response": "{}\n" }`
> 
> There must be some query parameters to add or a format issue. To what I found out, it stores the values in 31 days and that is the way it's rendered in the app. Anyone has more luck with it?
> 
> those guys here where able to pull the data: [iobroker-community-adapters/ioBroker.tesla-motors@5046063](https://github.com/iobroker-community-adapters/ioBroker.tesla-motors/commit/5046063acbab24859227880608c6a7bc9c702cc9)

I faced same issue with you. Did you find the solution?

**Comment by timdorr** [comment]
I'm going to close this out
