### ISSUE TITLE
Tiime for a new release?

### ISSUE THREAD

**Issue by distler** [timdorr/tesla-api#491]
The existing Rubygem is no longer able to acquire new access tokens. Replacing `client.rb` with the one from GIT solves the problem. But such hackery should not be necessary.

**Comment by timdorr** [comment]
I've only just added the ability to break apart auth and code validation into two parts so that you can run it through a browser to bypass the captcha. I'd really like to figure out how to reliably skip the captcha (it's not via just the request headers, as far as I can tell), so I'll give that a try and release once I've found out if it's possible or not.
