### ISSUE TITLE
"data_request" endpoints appear to have been removed by Tesla

### ISSUE THREAD

**Issue by jonahwh** [timdorr/tesla-api#711]
It appears that all the "data_request" endpoints (`data_request/charge_state`, `data_request/climate_state`, etc.) have been removed and are returning 404s.

These endpoints are no longer in the `owner_endpoints.json` file bundled with the app either.

It appears the only way to fetch vehicle state anymore is to use `/api/1/vehicles/{id}/vehicle_data`

**Comment by epologee** [comment]
I'm guessing it has been half a year since these endpoints were marked as deprecated, so they were removed, or maybe it's a phased rollout.

In addition to the `/data_request/*`-paths, the `/latest_vehicle_data` (caching the last vehicle_data server side) also got removed. These docs can be updated:

https://github.com/timdorr/tesla-api/blob/779fefb675e2684d1b7884430ab2c4de5c030854/docs/vehicle/state/data.md?plain=1#L216

The response from `/vehicle_data` also no longer contains the "legacy"-section.

If anyone knows where the `/latest_vehicle_data` went (maybe as a parameter on `/vehicle_data` ?), please do share.

**Comment by SylvainGa** [comment]
Which sucks since /vehicle_data returns way more data what the state API did. On devices with weak CPU (ie, watches), this makes a big differences in performance :-(

**Comment by osheroff** [comment]
@epologee hmmm where did you see the deprecation?
